[build]
  publish = "."
  functions = "functions"

[[redirects]]
  from = "/acceso"
  to = "/acceso.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/contenido/*"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
